import { Weapon } from '../types/Weapon';

export const BLASTERS: Weapon[] = [
    {
        type: 'BLASTER',
        id: 'luna-blaster_0',
        sub: 'splat-bomb',
        special: 'zipcaster',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/59/S3_Weapon_Main_Luna_Blaster.png',
    },
    {
        type: 'BLASTER',
        id: 'luna-blaster_1',
        sub: 'fizzy-bomb',
        special: 'ultra-stamp',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/1/11/S3_Weapon_Main_Luna_Blaster_Neo.png',
    },
    {
        type: 'BLASTER',
        id: 'blaster_0',
        sub: 'autobomb',
        special: 'big-bubbler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/a/a7/S3_Weapon_Main_Blaster.png',
    },
    {
        type: 'BLASTER',
        id: 'blaster_1',
        sub: 'point-sensor',
        special: 'triple-splashdown',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/4/44/S3_Weapon_Main_Custom_Blaster.png',
    },
    {
        type: 'BLASTER',
        id: 'range-blaster_0',
        sub: 'suction-bomb',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/1/1d/S3_Weapon_Main_Range_Blaster.png',
    },
    {
        type: 'BLASTER',
        id: 'range-blaster_1',
        sub: 'splat-bomb',
        special: 'kraken-royale',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/ce/S3_Weapon_Main_Custom_Range_Blaster.png',
    },
    {
        type: 'BLASTER',
        id: 'clash-blaster_0',
        sub: 'splat-bomb',
        special: 'trizooka',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/2f/S3_Weapon_Main_Clash_Blaster.png',
    },
    {
        type: 'BLASTER',
        id: 'clash-blaster_1',
        sub: 'curling-bomb',
        special: 'super-chump',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/1/10/S3_Weapon_Main_Clash_Blaster_Neo.png',
    },
    {
        type: 'BLASTER',
        id: 'rapid-blaster_0',
        sub: 'ink-mine',
        special: 'triple-inkstrike',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/6/6a/S3_Weapon_Main_Rapid_Blaster.png',
    },
    {
        type: 'BLASTER',
        id: 'rapid-blaster_1',
        sub: 'torpedo',
        special: 'inkjet',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/cb/S3_Weapon_Main_Rapid_Blaster_Deco.png',
    },
    {
        type: 'BLASTER',
        id: 'rapid-blaster-pro_0',
        sub: 'toxic-mist',
        special: 'ink-vac',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/c6/S3_Weapon_Main_Rapid_Blaster_Pro.png',
    },
    {
        type: 'BLASTER',
        id: 'rapid-blaster-pro_1',
        sub: 'angle-shooter',
        special: 'killer-wail-5.1',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/e/e4/S3_Weapon_Main_Rapid_Blaster_Pro_Deco.png',
    },
    {
        type: 'BLASTER',
        id: 's-blast_0',
        sub: 'sprinkler',
        special: 'reefslider',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/2d/S3_Weapon_Main_S-BLAST_%2792.png',
    },
    {
        type: 'BLASTER',
        id: 's-blast_0',
        sub: 'burst-bomb',
        special: 'booyah-bomb',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/2f/S3_Weapon_Main_S-BLAST_%2791.png',
    },
    {
        type: 'BLASTER',
        id: 'order-blaster-replica',
        sub: 'splat-bomb',
        special: 'zipcaster',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/7/7b/S3_Weapon_Main_Order_Blaster_Replica.png',
    },
];
