import { Weapon } from '../types/Weapon';

export const CHARGERS: Weapon[] = [
    {
        type: 'CHARGER',
        id: 'squiffer_0',
        sub: 'point-sensor',
        special: 'big-bubbler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/3/3c/S3_Weapon_Main_Classic_Squiffer.png',
    },
    {
        type: 'CHARGER',
        id: 'squiffer_1',
        sub: 'autobomb',
        special: 'zipcaster',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/80/S3_Weapon_Main_New_Squiffer.png',
    },
    {
        type: 'CHARGER',
        id: 'splat-charger_0',
        sub: 'splat-bomb',
        special: 'ink-vac',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/4/41/S3_Weapon_Main_Splat_Charger.png',
    },
    {
        type: 'CHARGER',
        id: 'splat-charger_1',
        sub: 'splash-wall',
        special: 'triple-inkstrike',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/a/a6/S3_Weapon_Main_Z%2BF_Splat_Charger.png',
    },
    {
        type: 'CHARGER',
        id: 'splatterscope_0',
        sub: 'splat-bomb',
        special: 'ink-vac',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/b/b2/S3_Weapon_Main_Splatterscope.png',
    },
    {
        type: 'CHARGER',
        id: 'splatterscope_1',
        sub: 'splash-wall',
        special: 'triple-inkstrike',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/86/S3_Weapon_Main_Z%2BF_Splatterscope.png',
    },
    {
        type: 'CHARGER',
        id: 'e-liter_0',
        sub: 'ink-mine',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/1/10/S3_Weapon_Main_E-liter_4K.png',
    },
    {
        type: 'CHARGER',
        id: 'e-liter_1',
        sub: 'squid-beakon',
        special: 'kraken-royale',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/e/e6/S3_Weapon_Main_Custom_E-liter_4K.png',
    },
    {
        type: 'CHARGER',
        id: 'e-liter-scope_0',
        sub: 'ink-mine',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/e/eb/S3_Weapon_Main_E-liter_4K_Scope.png',
    },
    {
        type: 'CHARGER',
        id: 'e-liter-scope_1',
        sub: 'squid-beakon',
        special: 'kraken-royale',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/7/7c/S3_Weapon_Main_Custom_E-liter_4K_Scope.png',
    },
    {
        type: 'CHARGER',
        id: 'bamboozler-14',
        sub: 'autobomb',
        special: 'killer-wail-5.1',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/6/6d/S3_Weapon_Main_Bamboozler_14_Mk_I.png',
    },
    {
        type: 'CHARGER',
        id: 'goo-tuber_0',
        sub: 'torpedo',
        special: 'tenta-missiles',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/8a/S3_Weapon_Main_Goo_Tuber.png',
    },
    {
        type: 'CHARGER',
        id: 'goo-tuber_1',
        sub: 'fizzy-bomb',
        special: 'ultra-stamp',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/9/91/S3_Weapon_Main_Custom_Goo_Tuber.png',
    },
    {
        type: 'CHARGER',
        id: 'snipewriter_0',
        sub: 'sprinkler',
        special: 'tacticooler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/3/34/S3_Weapon_Main_Snipewriter_5H.png',
    },
    {
        type: 'CHARGER',
        id: 'snipewriter_1',
        sub: 'splash-wall',
        special: 'ink-storm',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/0/0a/S3_Weapon_Main_Snipewriter_5B.png',
    },
    {
        type: 'CHARGER',
        id: 'order-charger-replica',
        sub: 'splat-bomb',
        special: 'ink-vac',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/0/00/S3_Weapon_Main_Order_Charger_Replica.png',
    },
];
