import { Weapon } from '../types/Weapon';

export const DUALIES: Weapon[] = [
    {
        type: 'DUALIE',
        id: 'dapple-dualies_0',
        sub: 'squid-beakon',
        special: 'tacticooler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/54/S3_Weapon_Main_Dapple_Dualies.png',
    },
    {
        type: 'DUALIE',
        id: 'dapple-dualies_1',
        sub: 'torpedo',
        special: 'reefslider',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/e/e1/S3_Weapon_Main_Dapple_Dualies_Nouveau.png',
    },
    {
        type: 'DUALIE',
        id: 'splat-dualies_0',
        sub: 'suction-bomb',
        special: 'crab-tank',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/e/e8/S3_Weapon_Main_Splat_Dualies.png',
    },
    {
        type: 'DUALIE',
        id: 'splat-dualies_1',
        sub: 'curling-bomb',
        special: 'triple-splashdown',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/4/46/S3_Weapon_Main_Enperry_Splat_Dualies.png',
    },
    {
        type: 'DUALIE',
        id: 'glooga-dualies_0',
        sub: 'splash-wall',
        special: 'booyah-bomb',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/9/99/S3_Weapon_Main_Glooga_Dualies.png',
    },
    {
        type: 'DUALIE',
        id: 'glooga-dualies_1',
        sub: 'point-sensor',
        special: 'trizooka',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/56/S3_Weapon_Main_Glooga_Dualies_Deco.png',
    },
    {
        type: 'DUALIE',
        id: 'dualie-squelchers_0',
        sub: 'splat-bomb',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/5a/S3_Weapon_Main_Dualie_Squelchers.png',
    },
    {
        type: 'DUALIE',
        id: 'dualie-squelchers_1',
        sub: 'squid-beakon',
        special: 'super-chump',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/9/9d/S3_Weapon_Main_Custom_Dualie_Squelchers.png',
    },
    {
        type: 'DUALIE',
        id: 'tetra-dualies_0',
        sub: 'autobomb',
        special: 'reefslider',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/c9/S3_Weapon_Main_Dark_Tetra_Dualies.png',
    },
    {
        type: 'DUALIE',
        id: 'tetra-dualies_1',
        sub: 'sprinkler',
        special: 'zipcaster',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/86/S3_Weapon_Main_Light_Tetra_Dualies.png',
    },
    {
        type: 'DUALIE',
        id: 'order-dualie-replicas',
        sub: 'suction-bomb',
        special: 'crab-tank',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/50/S3_Weapon_Main_Order_Dualie_Replicas.png',
    },
    {
        type: 'DUALIE',
        id: 'douser-dualies',
        sub: 'ink-mine',
        special: 'killer-wail-5.1',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/2c/S3_Weapon_Main_Douser_Dualies_FF.png',
    },
];
