import { Weapon } from '../types/Weapon';

export const SHOOTERS: Weapon[] = [
    {
        type: 'SHOOTER',
        id: 'sploosh-o-matic_0',
        sub: 'curling-bomb',
        special: 'ultra-stamp',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/59/S3_Weapon_Main_Sploosh-o-matic.png',
    },
    {
        type: 'SHOOTER',
        id: 'sploosh-o-matic_1',
        sub: 'squid-beakon',
        special: 'killer-wail-5.1',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/c3/S3_Weapon_Main_Neo_Sploosh-o-matic.png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-jr_0',
        sub: 'splat-bomb',
        special: 'big-bubbler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/1/1e/S3_Weapon_Main_Splattershot_Jr..png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-jr_1',
        sub: 'torpedo',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/d/df/S3_Weapon_Main_Custom_Splattershot_Jr..png',
    },
    {
        type: 'SHOOTER',
        id: 'splash-o-matic_0',
        sub: 'burst-bomb',
        special: 'crab-tank',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/7/7b/S3_Weapon_Main_Splash-o-matic.png',
    },
    {
        type: 'SHOOTER',
        id: 'splash-o-matic_1',
        sub: 'suction-bomb',
        special: 'triple-inkstrike',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/b/b8/S3_Weapon_Main_Neo_Splash-o-matic.png',
    },
    {
        type: 'SHOOTER',
        id: 'aerospray_0',
        sub: 'fizzy-bomb',
        special: 'reefslider',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/c5/S3_Weapon_Main_Aerospray_MG.png',
    },
    {
        type: 'SHOOTER',
        id: 'aerospray_1',
        sub: 'sprinkler',
        special: 'booyah-bomb',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/2b/S3_Weapon_Main_Aerospray_RG.png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot_0',
        sub: 'suction-bomb',
        special: 'trizooka',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/b/bf/S3_Weapon_Main_Splattershot.png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot_1',
        sub: 'splat-bomb',
        special: 'triple-inkstrike',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/f/f1/S3_Weapon_Main_Tentatek_Splattershot.png',
    },
    {
        type: 'SHOOTER',
        id: 'hero-shot-replica',
        sub: 'suction-bomb',
        special: 'trizooka',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/24/S3_Weapon_Main_Hero_Shot_Replica.png',
    },
    {
        type: 'SHOOTER',
        id: '52-gal',
        sub: 'splash-wall',
        special: 'killer-wail-5.1',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/e/ed/S3_Weapon_Main_.52_Gal.png',
    },
    {
        type: 'SHOOTER',
        id: 'n-zap_0',
        sub: 'suction-bomb',
        special: 'tacticooler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/f/f6/S3_Weapon_Main_N-ZAP_%2785.png',
    },
    {
        type: 'SHOOTER',
        id: 'n-zap_1',
        sub: 'autobomb',
        special: 'super-chump',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/9/98/S3_Weapon_Main_N-ZAP_%2789.png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-pro_0',
        sub: 'angle-shooter',
        special: 'crab-tank',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/7/77/S3_Weapon_Main_Splattershot_Pro.png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-pro_1',
        sub: 'suction-bomb',
        special: 'booyah-bomb',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/d/d8/S3_Weapon_Main_Forge_Splattershot_Pro.png',
    },
    {
        type: 'SHOOTER',
        id: '96-gal_0',
        sub: 'sprinkler',
        special: 'ink-vac',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/55/S3_Weapon_Main_.96_Gal.png',
    },
    {
        type: 'SHOOTER',
        id: '96-gal_1',
        sub: 'splash-wall',
        special: 'kraken-royale',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/8b/S3_Weapon_Main_.96_Gal_Deco.png',
    },
    {
        type: 'SHOOTER',
        id: 'jet-squelcher_0',
        sub: 'angle-shooter',
        special: 'ink-vac',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/6/69/S3_Weapon_Main_Jet_Squelcher.png',
    },
    {
        type: 'SHOOTER',
        id: 'jet-squelcher_1',
        sub: 'toxic-mist',
        special: 'ink-storm',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/e/ed/S3_Weapon_Main_Custom_Jet_Squelcher.png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-nova_0',
        sub: 'point-sensor',
        special: 'killer-wail-5.1',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/1/10/S3_Weapon_Main_Splattershot_Nova.png',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-nova_1',
        sub: 'ink-mine',
        special: 'inkjet',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/c5/S3_Weapon_Main_Annaki_Splattershot_Nova.png',
    },
    {
        type: 'SHOOTER',
        id: 'l-3-nozzlenose_0',
        sub: 'curling-bomb',
        special: 'crab-tank',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/2c/S3_Weapon_Main_L-3_Nozzlenose.png',
    },
    {
        type: 'SHOOTER',
        id: 'l-3-nozzlenose_1',
        sub: 'burst-bomb',
        special: 'ultra-stamp',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/f/ff/S3_Weapon_Main_L-3_Nozzlenose_D.png',
    },
    {
        type: 'SHOOTER',
        id: 'h-3-nozzlenose_0',
        sub: 'point-sensor',
        special: 'tacticooler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/5a/S3_Weapon_Main_H-3_Nozzlenose.png',
    },
    {
        type: 'SHOOTER',
        id: 'h-3-nozzlenose_1',
        sub: 'splash-wall',
        special: 'big-bubbler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/3/31/S3_Weapon_Main_H-3_Nozzlenose_D.png',
    },
    {
        type: 'SHOOTER',
        id: 'squeezer_0',
        sub: 'splash-wall',
        special: 'trizooka',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/cb/S3_Weapon_Main_Squeezer.png',
    },
    {
        type: 'SHOOTER',
        id: 'squeezer_1',
        sub: 'autobomb',
        special: 'splattercolor-screen',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/4/49/S3_Weapon_Main_Foil_Squeezer.png',
    },
];
