import { Weapon } from '../types/Weapon';

export const SHOOTERS: Weapon[] = [
    {
        type: 'SHOOTER',
        id: 'sploosh-o-matic_0',
        sub: 'curling-bomb',
        special: 'ultra-stamp',
    },
    {
        type: 'SHOOTER',
        id: 'sploosh-o-matic_1',
        sub: 'squid-beakon',
        special: 'killer-wail-5.1',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-jr_0',
        sub: 'splat-bomb',
        special: 'big-bubbler',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-jr_1',
        sub: 'torpedo',
        special: 'wave-breaker',
    },
    {
        type: 'SHOOTER',
        id: 'splash-o-matic_0',
        sub: 'burst-bomb',
        special: 'crab-tank',
    },
    {
        type: 'SHOOTER',
        id: 'splash-o-matic_1',
        sub: 'suction-bomb',
        special: 'triple-inkstrike',
    },
    {
        type: 'SHOOTER',
        id: 'aerospray_0',
        sub: 'fizzy-bomb',
        special: 'reefslider',
    },
    {
        type: 'SHOOTER',
        id: 'aerospray_1',
        sub: 'sprinkler',
        special: 'booyah-bomb',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot_0',
        sub: 'suction-bomb',
        special: 'trizooka',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot_1',
        sub: 'splat-bomb',
        special: 'triple-inkstrike',
    },
    {
        type: 'SHOOTER',
        id: '52-gal',
        sub: 'splash-wall',
        special: 'killer-wail-5.1',
    },
    {
        type: 'SHOOTER',
        id: 'n-zap_0',
        sub: 'suction-bomb',
        special: 'tacticooler',
    },
    {
        type: 'SHOOTER',
        id: 'n-zap_1',
        sub: 'autobomb',
        special: 'super-chump',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-pro_0',
        sub: 'angle-shooter',
        special: 'crab-tank',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-pro_1',
        sub: 'suction-bomb',
        special: 'booyah-bomb',
    },
    {
        type: 'SHOOTER',
        id: '96-gal_0',
        sub: 'sprinkler',
        special: 'ink-vac',
    },
    {
        type: 'SHOOTER',
        id: '96-gal_1',
        sub: 'splash-wall',
        special: 'kraken-royale',
    },
    {
        type: 'SHOOTER',
        id: 'jet-squelcher_0',
        sub: 'angle-shooter',
        special: 'ink-vac',
    },
    {
        type: 'SHOOTER',
        id: 'jet-squelcher_1',
        sub: 'toxic-mist',
        special: 'ink-storm',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-nova_0',
        sub: 'point-sensor',
        special: 'killer-wail-5.1',
    },
    {
        type: 'SHOOTER',
        id: 'splattershot-nova_1',
        sub: 'ink-mine',
        special: 'inkjet',
    },
    {
        type: 'SHOOTER',
        id: 'l-3-nozzlenose_0',
        sub: 'curling-bomb',
        special: 'crab-tank',
    },
    {
        type: 'SHOOTER',
        id: 'l-3-nozzlenose_1',
        sub: 'burst-bomb',
        special: 'ultra-stamp',
    },
    {
        type: 'SHOOTER',
        id: 'h-3-nozzlenose_0',
        sub: 'point-sensor',
        special: 'tacticooler',
    },
    {
        type: 'SHOOTER',
        id: 'h-3-nozzlenose_1',
        sub: 'splash-wall',
        special: 'big-bubbler',
    },
    {
        type: 'SHOOTER',
        id: 'squeezer',
        sub: 'splash-wall',
        special: 'trizooka',
    },
];
