import { Weapon } from '../types/Weapon';

export const SLOSHERS: Weapon[] = [
    {
        type: 'SLOSHER',
        id: 'slosher_0',
        sub: 'splat-bomb',
        special: 'triple-inkstrike',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/4/42/S3_Weapon_Main_Slosher.png',
    },
    {
        type: 'SLOSHER',
        id: 'slosher_1',
        sub: 'angle-shooter',
        special: 'zipcaster',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/a/a5/S3_Weapon_Main_Slosher_Deco.png',
    },
    {
        type: 'SLOSHER',
        id: 'tri-slosher_0',
        sub: 'toxic-mist',
        special: 'inkjet',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/d/dc/S3_Weapon_Main_Tri-Slosher.png',
    },
    {
        type: 'SLOSHER',
        id: 'tri-slosher_1',
        sub: 'fizzy-bomb',
        special: 'tacticooler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/7/74/S3_Weapon_Main_Tri-Slosher_Nouveau.png',
    },
    {
        type: 'SLOSHER',
        id: 'sloshing-machine_0',
        sub: 'fizzy-bomb',
        special: 'booyah-bomb',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/3/38/S3_Weapon_Main_Sloshing_Machine.png',
    },
    {
        type: 'SLOSHER',
        id: 'sloshing-machine_1',
        sub: 'point-sensor',
        special: 'trizooka',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/d/d5/S3_Weapon_Main_Sloshing_Machine_Neo.png',
    },
    {
        type: 'SLOSHER',
        id: 'bloblobber_0',
        sub: 'sprinkler',
        special: 'ink-storm',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/4/41/S3_Weapon_Main_Bloblobber.png',
    },
    {
        type: 'SLOSHER',
        id: 'bloblobber_1',
        sub: 'angle-shooter',
        special: 'kraken-royale',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/9/93/S3_Weapon_Main_Bloblobber_Deco.png',
    },
    {
        type: 'SLOSHER',
        id: 'explosher_0',
        sub: 'point-sensor',
        special: 'ink-storm',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/d/de/S3_Weapon_Main_Explosher.png',
    },
    {
        type: 'SLOSHER',
        id: 'explosher_1',
        sub: 'splash-wall',
        special: 'triple-splashdown',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/6/6e/S3_Weapon_Main_Custom_Explosher.png',
    },
    {
        type: 'SLOSHER',
        id: 'dread-wringer_0',
        sub: 'suction-bomb',
        special: 'reefslider',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/6/6c/S3_Weapon_Main_Dread_Wringer.png',
    },
    {
        type: 'SLOSHER',
        id: 'dread-wringer_1',
        sub: 'squid-beakon',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/d/d2/S3_Weapon_Main_Dread_Wringer_D.png',
    },
    {
        type: 'SLOSHER',
        id: 'order-slosher-replica',
        sub: 'splat-bomb',
        special: 'triple-inkstrike',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/a/aa/S3_Weapon_Main_Order_Slosher_Replica.png',
    },
];
