import { Weapon } from '../types/Weapon';

export const SPLATLINGS: Weapon[] = [
    {
        type: 'SPLATLING',
        id: 'mini-splatling_0',
        sub: 'burst-bomb',
        special: 'ultra-stamp',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/86/S3_Weapon_Main_Mini_Splatling.png',
    },
    {
        type: 'SPLATLING',
        id: 'mini-splatling_1',
        sub: 'toxic-mist',
        special: 'big-bubbler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/0/05/S3_Weapon_Main_Zink_Mini_Splatling.png',
    },
    {
        type: 'SPLATLING',
        id: 'heavy-splatling_0',
        sub: 'sprinkler',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/5/5e/S3_Weapon_Main_Heavy_Splatling.png',
    },
    {
        type: 'SPLATLING',
        id: 'heavy-splatling_1',
        sub: 'point-sensor',
        special: 'kraken-royale',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/f/fc/S3_Weapon_Main_Heavy_Splatling_Deco.png',
    },
    {
        type: 'SPLATLING',
        id: 'hydra-splatling_0',
        sub: 'autobomb',
        special: 'booyah-bomb',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/d/d1/S3_Weapon_Main_Hydra_Splatling.png',
    },
    {
        type: 'SPLATLING',
        id: 'hydra-splatling_1',
        sub: 'ink-mine',
        special: 'splattercolor-screen',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/f/f6/S3_Weapon_Main_Custom_Hydra_Splatling.png',
    },
    {
        type: 'SPLATLING',
        id: 'ballpoint-splatling_0',
        sub: 'fizzy-bomb',
        special: 'inkjet',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/f/f9/S3_Weapon_Main_Ballpoint_Splatling.png',
    },
    {
        type: 'SPLATLING',
        id: 'ballpoint-splatling_1',
        sub: 'ink-mine',
        special: 'ink-vac',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/b/b1/S3_Weapon_Main_Ballpoint_Splatling_Nouveau.png',
    },
    {
        type: 'SPLATLING',
        id: 'nautilus_0',
        sub: 'point-sensor',
        special: 'ink-storm',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/81/S3_Weapon_Main_Nautilus_47.png',
    },
    {
        type: 'SPLATLING',
        id: 'nautilus_1',
        sub: 'suction-bomb',
        special: 'triple-splashdown',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/8/81/S3_Weapon_Main_Nautilus_79.png',
    },
    {
        type: 'SPLATLING',
        id: 'heavy-edit-splatling_0',
        sub: 'curling-bomb',
        special: 'tacticooler',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/2/24/S3_Weapon_Main_Heavy_Edit_Splatling.png',
    },
    {
        type: 'SPLATLING',
        id: 'heavy-edit-splatling_1',
        sub: 'splat-bomb',
        special: 'crab-tank',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/a/aa/S3_Weapon_Main_Heavy_Edit_Splatling_Nouveau.png',
    },
    {
        type: 'SPLATLING',
        id: 'order-splatling-replica',
        sub: 'sprinkler',
        special: 'wave-breaker',
        iconUrl: 'https://cdn.wikimg.net/en/splatoonwiki/images/c/ce/S3_Weapon_Main_Order_Splatling_Replica.png',
    },
];
